### PR TITLE
Update MagSafeController.xm

### PR DESCRIPTION
**Pull request by anynon**

### CODE REVIEW

**Comment by tomaszpoliszuk** [comment]
I've used this one in my other tweaks and also detecting by kCFCoreFoundationVersionNumber but:
- i know from where kCFCoreFoundationVersionNumber comes from (supported since iOS 1 or 2)
- i know from [NSProcessInfo processInfo] isOperatingSystemAtLeastVersion: comes from (supported since iOS 8 or 9)
- i don't know `@available` (didn't have time to investigate it yet) - could you enlighten me?

I'm asking since I will most likely implement the same one and for now `@available` one is unknown :)

**Comment by tomaszpoliszuk** [comment]
I've finally found what's up with `@available` - it's supported in similar versions as `isOperatingSystemAtLeastVersion` but looks cleaner - I'll use it for now but eventually I'll switch to `kCFCoreFoundationVersionNumber` as soon as I figure out what version number iOS 14.1 have.

Thanks, approved.

**Comment by anynon** [comment]
The kCFCoreFoundationVersionNumber for iOS 14.0 is 1740.00. I imagine iOS 14.1 is 1741 or somewhere close to that. Sorry for the late response. This is the only documentation I could find on it  : [clang.llvm.org/docs/LanguageExtensions.html#objective-c-available](http://clang.llvm.org/docs/LanguageExtensions.html#objective-c-available)

Personally, the only reason I prefer it is the complier does optimizations with it like omitting it if building for iOS 14.1 which the alternatives do not.

**Comment by tomaszpoliszuk** [comment]
> kCFCoreFoundationVersionNumber for iOS 14.0 is 1740.00

That part I've found and if not i would use it but unfortunately there 14.0.1 exist (otherwise i would just use `kCFCoreFoundationVersionNumber > 1740.00`)

> Sorry for the late response.

There's no need to do that - it wasn't issue :)

> Personally, the only reason I prefer it is the compiler does optimizations with it like omitting it if building for iOS 14.1 which the alternatives do not.

This is good info - I didn't know that - maybe I'll end with combination of `kCFCoreFoundationVersionNumber` and `@available` (some wrapper around both of them perhaps?)

Oh and changing domainString to const was sweet since it shouldn't change anywhere in code :)

Thank you and have nice day!

**Comment by tomaszpoliszuk** [comment]
Just in case you need it for something - `kCFCoreFoundationVersionNumber` for iOS 14.0.1 is `1751.108` - just checked on 6s

**Comment by enad-111** [comment]
1

**Pull request merged**
